apiVersion: hivemq.com/v1
kind: HiveMQCluster
metadata:
  name: hivemq-cluster1
  namespace: hivemq
spec:
  hivemqVersion: 0.1.1-4.2.2
  image: sbaier1/hivemq-k8s
  imagePullPolicy: Always
  nodeCount: 2
  logLevel: INFO
  mqtt:
    maxQos: 2
  monitoring:
    enablePrometheus: true
  memory: '4096M'
  # This will result in 4 cpu cores being requested, but we can overcommit to all 8.
  cpu: '1000m'
  extensions:
    - name: hivemq-kafka-extension
      extensionUri: https://www.hivemq.com/releases/extensions/hivemq-kafka-extension-1.0.0.zip
      configMap: kafka-config
